### ISSUE TITLE
Which waymo dataset should i download. Can you share dataset format?

### ISSUE THREAD

**Issue by geyikciomer** [LightwheelAI/street-gaussians-ns#2]

**Comment by LightwheelAI** [comment]
Thanks for your issue, we use waymo percetion v1.4.0 to test our model, you can download the dataset here https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_4_0 and we update our readme to detail the dataset format as follow
```
clip root
  |-- images
  |     |-- ${cam0 name}
  |     |   |-- t0.jpg/png
  |     |   |-- t1.jpg/png
  |     |   |-- ...
  |     |
  |     |-- ${cam1 name}
  |     |-- ...
  |
  |-- lidars
  |     |-- ${lidar0 name}
  |     |   |-- t0.pcd
  |     |   |-- t1.pcd
  |     |   |-- ...
  |     |
  |     |-- ${lidar1 name}
  |     |-- ...
  |
  |-- transform.json
  |-- annotation.json
```

**Comment by geyikciomer** [comment]
Thank you for your work. We have three cameras on front and one lidar, do you think this repo fits our data?

**Comment by LightwheelAI** [comment]
We have fitten 6 cameras in our dataparser, it can be helpful to change the ```--filter_camera_id``` to use other cameras referring to ```scripts/shells/train.sh```.
best
