### ISSUE TITLE
`sgn_train` Not found for train.sh

### ISSUE THREAD

**Issue by muye1202** [LightwheelAI/street-gaussians-ns#21]
May I ask in what package is sgn_train command installed? Is it from the nerfstudio package?

thanks

**Comment by muye1202** [comment]
It seems sgn_train comes from nerfstudio

**Comment by Hamme122** [comment]
Hi, I think it's in the pyproject.toml file. And do you know how to debug this command, thank you!

**Comment by muye1202** [comment]
> Hi, I think it's in the pyproject.toml file. And do you know how to debug this command, thank you!

Hi! If you meant a closer look at the training pipeline source code, I think sgn_train related config is defined in 'sgn_config.py', and the sgn related model classes inherit from Nerfstudio classes. Arguments such as loading model checkpoints can be found in 'sgn_config.py'
