### ISSUE TITLE
project_gaussians() missing 1 required positional argument: 'tile_bounds'

### ISSUE THREAD

**Issue by mzlchou** [LightwheelAI/street-gaussians-ns#28]
I'm trying to train the preprocessed 10588771936253546636 sequence, but I am running into the project_gaussians() missing 1 required positional argument: 'tile_bounds'. I'm not really sure how I solve this issue thanks so much.

**Comment by MrChaa** [comment]
same error when training with preprocessed dataset

**Comment by achao2013** [comment]
gspat version >0.1.9

**Comment by mzlchou** [comment]
> use gsplat with version >=0.1.9 , ignore nerfstudio incompatible problem. @MrChaa @mzlchou

When I try this I get "ImportError: cannot import name 'csrc' from 'gsplat'" and raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1. I added the cl directory to path so I dont really know what this means.

**Comment by 1400013531** [comment]
another issue reported the same problem https://github.com/LightwheelAI/street-gaussians-ns/issues/31 
gsplat to 0.1.11 and nerfstudio to 1.1.0 worked for me.
