### ISSUE TITLE
About the waymo percetion v1.4.0 dataset used in your work.

### ISSUE THREAD

**Issue by FudongGe** [LightwheelAI/street-gaussians-ns#3]
Hi,
Thanks for your excellent work! But the waymo percetion v1.4.0 dataset is too large, so could you explain the specific sequences used in your work for training and testing? Or have you used all the training, validation and testing datasets?
Thanks for your attention.

**Comment by LightwheelAI** [comment]
Thanks for your issue, we used sequences 10448102132863604198, 2094681306939952000 and 8398516118967750070 of validation dataset to test the model in this repo. 
best

**Comment by FudongGe** [comment]
Hi, thanks for your response. But I met a problem again, that is "KeyError: "No object named 'MaskFormer' found in 'META_ARCH' registry!"". It seems that the MaskFormer isn't registered in the META_ARCH. The truth is that only the below models are registered. Did you meet the same question?
![image](https://github.com/LightwheelAI/street-gaussians-ns/assets/110442983/8b2812a5-ec56-4872-ad77-5b667394e79c)

**Comment by seasideGargantua** [comment]
I think this could be helpful https://github.com/LightwheelAI/street-gaussians-ns/issues/1#issuecomment-2127463228

**Comment by FudongGe** [comment]
> I think this could be helpful [#1 (comment)](https://github.com/LightwheelAI/street-gaussians-ns/issues/1#issuecomment-2127463228)

Oh, thanks for your help.

**Comment by GG-Bonds** [comment]
> 感谢您的问题，我们使用验证数据集的序列 10448102132863604198、2094681306939952000 和 8398516118967750070 来测试此 repo 中的模型。 最好



> 感谢您的问题，我们使用验证数据集的序列 10448102132863604198、2094681306939952000 和 8398516118967750070 来测试此 repo 中的模型。 最好
This link cannot download data

**Comment by GG-Bonds** [comment]
> 感谢您的问题，我们使用验证数据集的序列 10448102132863604198、2094681306939952000 和 8398516118967750070 来测试此 repo 中的模型。 最好



> 感谢您的问题，我们使用验证数据集的序列 10448102132863604198、2094681306939952000 和 8398516118967750070 来测试此 repo 中的模型。 最好

This link cannot download data
