### ISSUE TITLE
train issues

### ISSUE THREAD

**Issue by KL-2** [LightwheelAI/street-gaussians-ns#36]
I follow the instructions,when training,I meet this,can anyone help me?
bash scripts/shells/train.sh data/waymo_10448102132863604198_472_000_492_000/10448102132863604198_472_000_492_000/ 0
/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/tyro/_resolver.py:437: UserWarning: <class 'street_gaussians_ns.data.sgn_dataparser.ColmapDataParserConfig'> does not match any type in Union: [<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig'>, <class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig'>, <class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig'>, <class 'nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannetpp_dataparser.ScanNetppDataParserConfig'>, <class 'nerfstudio.data.dataparsers.colmap_dataparser.ColmapDataParserConfig'>]

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/street-gaussians-ns/bin/sgn-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 153, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 255, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_datamanager.py", line 100, in __init__
    self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs)
  File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 444, in _generate_dataparser_outputs
    metadata.update(self._load_3D_points(colmap_path, transform_matrix, scale_factor))
  File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 478, in _load_3D_points
    assert points_filepath.exists()
AssertionError

my gsplat   is     0.1.11,nerfstudio        is  1.1.0

**Comment by YifanJiang111** [comment]
> I follow the instructions,when training,I meet this,can anyone help me? bash scripts/shells/train.sh data/waymo_10448102132863604198_472_000_492_000/10448102132863604198_472_000_492_000/ 0 /home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/tyro/_resolver.py:437: UserWarning: <class 'street_gaussians_ns.data.sgn_dataparser.ColmapDataParserConfig'> does not match any type in Union: [<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig'>, <class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig'>, <class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig'>, <class 'nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannetpp_dataparser.ScanNetppDataParserConfig'>, <class 'nerfstudio.data.dataparsers.colmap_dataparser.ColmapDataParserConfig'>]
> 
> Traceback (most recent call last): File "/home/user/anaconda3/envs/street-gaussians-ns/bin/sgn-train", line 8, in sys.exit(entrypoint()) File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint main( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main launch( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch main_func(local_rank=0, world_size=world_size, config=config) File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop trainer.setup() File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 153, in setup self.pipeline = self.config.pipeline.setup( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup return self._target(self, **kwargs) File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 255, in **init** self.datamanager: DataManager = config.datamanager.setup( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup return self._target(self, **kwargs) File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_datamanager.py", line 100, in **init** self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train") File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs) File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 444, in _generate_dataparser_outputs metadata.update(self._load_3D_points(colmap_path, transform_matrix, scale_factor)) File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 478, in _load_3D_points assert points_filepath.exists() AssertionError
> 
> my gsplat is 0.1.11,nerfstudio is 1.1.0

This is probably because you're missing the points3D_withlidar.txt, which you can generate with street-gaussians-ns/scripts/shells/points_cloud_generate.sh

**Comment by KL-2** [comment]
> > I follow the instructions,when training,I meet this,can anyone help me? bash scripts/shells/train.sh data/waymo_10448102132863604198_472_000_492_000/10448102132863604198_472_000_492_000/ 0 /home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/tyro/_resolver.py:437: UserWarning: <class 'street_gaussians_ns.data.sgn_dataparser.ColmapDataParserConfig'> does not match any type in Union: [<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.minimal_dataparser.MinimalDataParserConfig'>, <class 'nerfstudio.data.dataparsers.arkitscenes_dataparser.ARKitScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.blender_dataparser.BlenderDataParserConfig'>, <class 'nerfstudio.data.dataparsers.instant_ngp_dataparser.InstantNGPDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nuscenes_dataparser.NuScenesDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dnerf_dataparser.DNeRFDataParserConfig'>, <class 'nerfstudio.data.dataparsers.phototourism_dataparser.PhototourismDataParserConfig'>, <class 'nerfstudio.data.dataparsers.dycheck_dataparser.DycheckDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannet_dataparser.ScanNetDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sdfstudio_dataparser.SDFStudioDataParserConfig'>, <class 'nerfstudio.data.dataparsers.nerfosr_dataparser.NeRFOSRDataParserConfig'>, <class 'nerfstudio.data.dataparsers.sitcoms3d_dataparser.Sitcoms3DDataParserConfig'>, <class 'nerfstudio.data.dataparsers.scannetpp_dataparser.ScanNetppDataParserConfig'>, <class 'nerfstudio.data.dataparsers.colmap_dataparser.ColmapDataParserConfig'>]
> > Traceback (most recent call last): File "/home/user/anaconda3/envs/street-gaussians-ns/bin/sgn-train", line 8, in sys.exit(entrypoint()) File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint main( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main launch( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch main_func(local_rank=0, world_size=world_size, config=config) File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop trainer.setup() File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 153, in setup self.pipeline = self.config.pipeline.setup( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup return self._target(self, **kwargs) File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 255, in **init** self.datamanager: DataManager = config.datamanager.setup( File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/configs/base_config.py", line 54, in setup return self._target(self, **kwargs) File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_datamanager.py", line 100, in **init** self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train") File "/home/user/anaconda3/envs/street-gaussians-ns/lib/python3.8/site-packages/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs) File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 444, in _generate_dataparser_outputs metadata.update(self._load_3D_points(colmap_path, transform_matrix, scale_factor)) File "/home/user/software/street-gaussians-ns/street_gaussians_ns/data/sgn_dataparser.py", line 478, in _load_3D_points assert points_filepath.exists() AssertionError
> > my gsplat is 0.1.11,nerfstudio is 1.1.0
> 
> This is probably because you're missing the points3D_withlidar.txt, which you can generate with street-gaussians-ns/scripts/shells/points_cloud_generate.sh

thanks,I run 
h scripts/shells/points_cloud_generate.sh data/waymo_10448102132863604198_472_000_492_000/10448102132863604198_472_000_492_000/
it's ok

while when I run sh scripts/shells/object_pts_generate.sh data/waymo_10448102132863604198_472_000_492_000/10448102132863604198_472_000_492_000/
100%|████████████████████████████████████| 915/915 [02:25<00:00,  6.28it/s]
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
[Open3D WARNING] Write PLY failed: point cloud has 0 points.
the result is like this,did you met this before
in folder sparse/0 I get points3D_withlidar.bin dont get the points3D_withlidar.txt

**Comment by KL-2** [comment]
![1](https://github.com/user-attachments/assets/5af92c66-9a49-4013-b8c8-10d7c95cc4fe)
I replaced    --init_points_filename points3D_withlidar.bin in train.sh to --init_points_filename points3D_withlidar.txt

the code can run like the photo.
Can I ignore the warning of [Open3D WARNING] Write PLY failed: point cloud has 0 points?
Is this right?

**Comment by YifanJiang111** [comment]
> ![1](https://private-user-images.githubusercontent.com/76254409/351560955-5af92c66-9a49-4013-b8c8-10d7c95cc4fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDcyMjEsIm5iZiI6MTcyMTgwNjkyMSwicGF0aCI6Ii83NjI1NDQwOS8zNTE1NjA5NTUtNWFmOTJjNjYtOWE0OS00MDEzLWI4YzgtMTBkN2M5NWNjNGZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA3NDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NWYwMGE0Nzg4ZWJkNzc2ZDFhYTc4OGFiZmIxZTUzMTZhNjI0NDM5OTI5OTliOTgzYzNjODM4Mjc4YmQzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UKlzK2qdVC8PZVAOHiDJwfrpsDw7ldwnIhsgjax3Ono) I replaced --init_points_filename points3D_withlidar.bin in train.sh to --init_points_filename points3D_withlidar.txt
> 
> the code can run like the photo. Can I ignore the warning of [Open3D WARNING] Write PLY failed: point cloud has 0 points? Is this right?

I hadn't met this problem, maybe you can see if you end up with the right rendered results

**Comment by KL-2** [comment]
> > ![1](https://private-user-images.githubusercontent.com/76254409/351560955-5af92c66-9a49-4013-b8c8-10d7c95cc4fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDcyMjEsIm5iZiI6MTcyMTgwNjkyMSwicGF0aCI6Ii83NjI1NDQwOS8zNTE1NjA5NTUtNWFmOTJjNjYtOWE0OS00MDEzLWI4YzgtMTBkN2M5NWNjNGZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA3NDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NWYwMGE0Nzg4ZWJkNzc2ZDFhYTc4OGFiZmIxZTUzMTZhNjI0NDM5OTI5OTliOTgzYzNjODM4Mjc4YmQzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UKlzK2qdVC8PZVAOHiDJwfrpsDw7ldwnIhsgjax3Ono) I replaced --init_points_filename points3D_withlidar.bin in train.sh to --init_points_filename points3D_withlidar.txt
> > the code can run like the photo. Can I ignore the warning of [Open3D WARNING] Write PLY failed: point cloud has 0 points? Is this right?
> 
> I hadn't met this problem, maybe you can see if you end up with the right rendered results

thanks

**Comment by lsrrrrrrrrr** [comment]
When i use the provided dataset (10588771936253546636_2300_000_2320_000), i met the same problem. The solution is to change the parameter "--init_points_filename" from "points3D_withlidar.txt" to "points3D.bin".
