### ISSUE TITLE
About the versions of waymo_open_dataset and tensorflow

### ISSUE THREAD

**Issue by FudongGe** [LightwheelAI/street-gaussians-ns#4]
Hi,

Thanks for your excellent work! And could you explain the versions of waymo_open_dataset and tensorflow? I have tried, but the version of nerfstudio may conflict with their versions.

Thanks for your attention.

**Comment by LightwheelAI** [comment]
Thanks for your issue. Here is our env setting, hope it could be helpful!
best
```
tensorflow 2.11.0
tensorflow-addons 0.23.0
tensorflow-datasets 4.9.0
tensorflow-estimator 2.11.0
tensorflow-graphics 2021.12.3
tensorflow-io-gcs-filesystem 0.36.0
tensorflow-metadata 1.13.0
tensorflow-probability 0.19.0
waymo-open-dataset-tf-2-11-0 1.6.1
```

**Comment by Ilareina** [comment]
Hi, after creating an environment under python3.8 as the guideline did, I can only install  `tensorflow-addons 0.21.0` and `tensorflow-io-gcs-filesystem 0.34.0` as `tensorflow-addons 0.23.0` and `tensorflow-io-gcs-filesystem 0.36.0` only exist for python>=3.9. In this condition, I received the following results when running `python scripts/python/extract_waymo.py --waymo_root path/to/your/waymo_root --out_root path/to/your/out_root`.
![1716816699250](https://github.com/LightwheelAI/street-gaussians-ns/assets/105036770/8c9bd9e8-39e0-4a5b-aede-2219409f54c1)

However, if I try to build env using python-3.9, it occurs `ERROR: Could not find a version that satisfies the requirement pytorch3d` when installing street-gaussians-ns. 

Looking forward to your help. Thanks.

**Comment by LightwheelAI** [comment]
Hi, this looks like a CUDA version issue, make sure your CUDA version corresponds to your pytorch version!

best

**Comment by markinruc** [comment]
> Hi, after creating an environment under python3.8 as the guideline did, I can only install `tensorflow-addons 0.21.0` and `tensorflow-io-gcs-filesystem 0.34.0` as `tensorflow-addons 0.23.0` and `tensorflow-io-gcs-filesystem 0.36.0` only exist for python>=3.9. In this condition, I received the following results when running `python scripts/python/extract_waymo.py --waymo_root path/to/your/waymo_root --out_root path/to/your/out_root`. ![1716816699250](https://private-user-images.githubusercontent.com/105036770/334119732-8c9bd9e8-39e0-4a5b-aede-2219409f54c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjc5NzAsIm5iZiI6MTcxNzEyNzY3MCwicGF0aCI6Ii8xMDUwMzY3NzAvMzM0MTE5NzMyLThjOWJkOWU4LTM5ZTAtNGE1Yi1hZWRlLTIyMTk0MDlmNTRjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwMzU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2YwOTA1ZGQ3YjA5NmIzMzEwZDZhNzJkMTY1ZmQyYzY4ZThmNTRmODVlYTc5YWE3NDE1ZDgyYTk1NjI5ZjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZAx7-SS8YzDfhv6r5aKaItauPCt7uuBui1tFIPkrwNI)
> 
> However, if I try to build env using python-3.9, it occurs `ERROR: Could not find a version that satisfies the requirement pytorch3d` when installing street-gaussians-ns.
> 
> Looking forward to your help. Thanks.
@Ilareina 
I think there is a problem with your Waymo data path. Pay attention to the regular expression for this.
![image](https://github.com/LightwheelAI/street-gaussians-ns/assets/72591695/2dc86ad3-2a7a-49d0-9c6d-c376f9a91366)
Your TFRecord files need to be placed in the directory not the root so that the extraction code can find them.
