### ISSUE TITLE
Changing render position

### ISSUE THREAD

**Issue by mzlchou** [LightwheelAI/street-gaussians-ns#50]
Does anybody know how I can adjust the camera position when rendering? It uses the original camera locations but is there a way I can slightly adjust it (for example to the right a couple units) and then render it using a different position? I assume there is a place that the positions are stored that I can just edit but I can't figure it out. Thanks.

**Comment by zzz5y** [comment]
hello,I wonder how you do this.
Can you give me any advice or code
Thank you so much

**Comment by zzz5y** [comment]
hello,I wonder how you do this.
Can you give me any advice or code
Thank you so much
