### ISSUE TITLE
The way to edit the scene

### ISSUE THREAD

**Issue by zwlvd** [LightwheelAI/street-gaussians-ns#7]
I wonder how to edit the object in the scene like the paper shows

**Comment by LightwheelAI** [comment]
Street gaussians decomposites background and dynamic objects and reconstructs them. We can control the dynamic objects by bounding box.

**Comment by PeterNg15** [comment]
Hi! Is there a script provided? I would like to reproduce it but not sure where to start. A script would be very helpful, thanks
